### ISSUE TITLE
Fix bug in `download_all` call

### ISSUE THREAD

**Issue by lgbouma** [HarritonResearchLab/sunnyhills#9]
https://github.com/HarritonResearchLab/sunnyhills/blob/c05b2906edb370e9791eaf9e8c2c0aa592bc7094/sunnyhills/pipeline_functions.py#L25

Consider the following test case:
```
import lightkurve as lk
lk.search_lightcurve('TIC 89463560').download_all()
```

When run, this will produce a nasty looking download stack traces including two different errors, one saying `TypeError: buffer is too small for requested array`, the other saying `ValueError: ``time_column`` should be provided since the default Table readers are being used`.

The reason turns out to be that lightkurve's `download_all` fails when there are certain combinations of heterogeneous light curve products.  This could probably be interpreted as a bug in lightkurve's behavior itself.  The solution for our use case would be to substitute all `download_all` calls with

```
ticstr = 'TIC 89463560'
lcset = lk.search_lightcurve(ticstr)
lcc = lcset[(lcset.author=='SPOC') & (lcset.exptime.value==120)].download_all()
```

**Comment by lgbouma** [comment]
NB, an even more robust pattern would be:

```
ticstr = 'TIC 89463560'
lcset = lk.search_lightcurve(ticstr)
if len(lcset) > 0:
    lcc = lcset[(lcset.author=='SPOC') & (lcset.exptime.value==120)].download_all()
```

otherwise it'll fail for TIC IDs without 120 second cadence data.

**Comment by thissop** [comment]
implemented thx for pointing out👍
